#!/bin/bash
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN
mkdir -p '/tmp/app/.next/server/pages'
echo '[x-amplify-log][INFO] starting copy'
cp -r '/var/task/.next/server/pages' '/tmp/app/.next/server'
echo '[x-amplify-log][INFO] copy server pages complete'
cp -f /var/task/server.js /tmp/app/server.js
echo '[x-amplify-log][INFO] copy complete'
ln -sf '/var/task/.env.production' '/tmp/app/.env.production'
ln -sf '/var/task/amplify-compute-bundle-output' '/tmp/app/amplify-compute-bundle-output'
ln -sf '/var/task/node_modules' '/tmp/app/node_modules'
ln -sf '/var/task/package.json' '/tmp/app/package.json'
ln -sf '/var/task/public' '/tmp/app/public'
echo '[x-amplify-log][INFO] Root symlink creation complete'
ln -sf '/var/task/.next/BUILD_ID' '/tmp/app/.next/BUILD_ID'
ln -sf '/var/task/.next/app-build-manifest.json' '/tmp/app/.next/app-build-manifest.json'
ln -sf '/var/task/.next/app-path-routes-manifest.json' '/tmp/app/.next/app-path-routes-manifest.json'
ln -sf '/var/task/.next/build-manifest.json' '/tmp/app/.next/build-manifest.json'
ln -sf '/var/task/.next/export-marker.json' '/tmp/app/.next/export-marker.json'
ln -sf '/var/task/.next/images-manifest.json' '/tmp/app/.next/images-manifest.json'
ln -sf '/var/task/.next/next-minimal-server.js.nft.json' '/tmp/app/.next/next-minimal-server.js.nft.json'
ln -sf '/var/task/.next/next-server.js.nft.json' '/tmp/app/.next/next-server.js.nft.json'
ln -sf '/var/task/.next/package.json' '/tmp/app/.next/package.json'
ln -sf '/var/task/.next/prerender-manifest.js' '/tmp/app/.next/prerender-manifest.js'
ln -sf '/var/task/.next/prerender-manifest.json' '/tmp/app/.next/prerender-manifest.json'
ln -sf '/var/task/.next/react-loadable-manifest.json' '/tmp/app/.next/react-loadable-manifest.json'
ln -sf '/var/task/.next/required-server-files.json' '/tmp/app/.next/required-server-files.json'
ln -sf '/var/task/.next/routes-manifest.json' '/tmp/app/.next/routes-manifest.json'
ln -sf '/var/task/.next/static' '/tmp/app/.next/static'
ln -sf '/var/task/.next/trace' '/tmp/app/.next/trace'
ln -sf '/var/task/.next/types' '/tmp/app/.next/types'
echo '[x-amplify-log][INFO] symlink creation complete path=.next'
ln -sf '/var/task/.next/server/app' '/tmp/app/.next/server/app'
ln -sf '/var/task/.next/server/app-paths-manifest.json' '/tmp/app/.next/server/app-paths-manifest.json'
ln -sf '/var/task/.next/server/chunks' '/tmp/app/.next/server/chunks'
ln -sf '/var/task/.next/server/edge-runtime-webpack.js' '/tmp/app/.next/server/edge-runtime-webpack.js'
ln -sf '/var/task/.next/server/edge-runtime-webpack.js.map' '/tmp/app/.next/server/edge-runtime-webpack.js.map'
ln -sf '/var/task/.next/server/font-manifest.json' '/tmp/app/.next/server/font-manifest.json'
ln -sf '/var/task/.next/server/middleware-build-manifest.js' '/tmp/app/.next/server/middleware-build-manifest.js'
ln -sf '/var/task/.next/server/middleware-manifest.json' '/tmp/app/.next/server/middleware-manifest.json'
ln -sf '/var/task/.next/server/middleware-react-loadable-manifest.js' '/tmp/app/.next/server/middleware-react-loadable-manifest.js'
ln -sf '/var/task/.next/server/middleware.js' '/tmp/app/.next/server/middleware.js'
ln -sf '/var/task/.next/server/middleware.js.map' '/tmp/app/.next/server/middleware.js.map'
ln -sf '/var/task/.next/server/next-font-manifest.js' '/tmp/app/.next/server/next-font-manifest.js'
ln -sf '/var/task/.next/server/next-font-manifest.json' '/tmp/app/.next/server/next-font-manifest.json'
ln -sf '/var/task/.next/server/pages-manifest.json' '/tmp/app/.next/server/pages-manifest.json'
ln -sf '/var/task/.next/server/server-reference-manifest.js' '/tmp/app/.next/server/server-reference-manifest.js'
ln -sf '/var/task/.next/server/server-reference-manifest.json' '/tmp/app/.next/server/server-reference-manifest.json'
ln -sf '/var/task/.next/server/webpack-runtime.js' '/tmp/app/.next/server/webpack-runtime.js'
ln -sf '/var/task/.next/server/webpack-runtime.js.map' '/tmp/app/.next/server/webpack-runtime.js.map'
echo '[x-amplify-log][INFO] symlink creation complete path=.next/server'
echo '[x-amplify-log][INFO] Starting Server'
source /opt/credential-listener/node_options.sh >/dev/null 2>&1 || true
node /tmp/app/server.js